// Headless smoke test: serve dist/ via the agent server, boot the Cesium app in Chromium (SwiftShader), run agent verbs, take screenshots.
// Usage: npm run build && node scripts/smoke.mjs [outDir]   (needs Playwright + Chromium; set PW_CHROME to the chrome binary if not auto-found)
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const req = createRequire(process.env.PW_REQUIRE_FROM || import.meta.url);
let pw; try { pw = req('playwright'); } catch { pw = createRequire('/opt/node22/lib/node_modules/')('playwright'); }
const out = process.argv[2] || 'dist'; fs.mkdirSync(out, { recursive: true });
const PORT = +(process.env.SMOKE_PORT || 8790); const server = spawn('node', ['server/index.mjs'], { env: { PEAKLENS_DEMO_LIVE: process.env.PEAKLENS_DEMO_LIVE || '1', ...process.env, PORT: String(PORT) }, stdio: ['ignore', 'pipe', 'pipe'] });
server.stdout.on('data', d => process.stdout.write('[server] ' + d)); server.stderr.on('data', d => process.stdout.write('[server:err] ' + d));
await new Promise(r => setTimeout(r, 800));
const wait = ms => new Promise(r => setTimeout(r, ms));
// Always bypass the sandbox proxy: Chromium routes localhost through a configured proxy (405) even with a bypass list; external tiles simply fail, which the app tolerates.
const browser = await pw.chromium.launch({ executablePath: process.env.PW_CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-proxy-server', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--no-sandbox', '--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, ignoreHTTPSErrors: true });
page.setDefaultTimeout(120000); // SwiftShader frames can take many seconds when animations are running
const errors = []; const expected = []; page.on('response', r => { if (r.status() >= 400 && !/favicon/.test(r.url())) (r.status() === 503 && /\/api\/(tdx\/s2s|walkshed)/.test(r.url()) ? expected : errors).push('http ' + r.status() + ' ' + r.url()); }); page.on('pageerror', e => errors.push('pageerror: ' + e.message)); page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') { const t = m.text(); if (!/fonts.googleapis|ERR_CONNECTION|net::|favicon|images.pickpeak/.test(t)) (/503 \(Service Unavailable\)|改用估算圈/.test(t) ? expected : errors).push(m.type() + ': ' + t.slice(0, 300)); } });
const t0 = Date.now();
try {
  await page.goto(`http://localhost:${PORT}/`, { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('#loading.done', { timeout: 240000 });
  console.log('booted in', Date.now() - t0, 'ms');
  await wait(9500); // cinematic intro (≈6.2 s) + settle
  const st = await page.evaluate(() => ({ osm: window.PL.osm ? window.PL.osm.count : null, entities: window.PL.layers.byKey.size, readout: document.querySelector('#readout .line').textContent, coords: document.querySelector('#readout .coords').textContent, inView: window.PL.map.countInView(), fps: 'n/a', imageryLayers: window.PL.viewer.imageryLayers.length, neReady: window.PL.viewer.imageryLayers.get(0).ready }));
  console.log('state', JSON.stringify(st));
  await page.screenshot({ path: path.join(out, 'shot-1-overview.jpg'), type: 'jpeg', quality: 84 });
  const say = async (t, ms) => { await page.evaluate(t => window.PL.ui.say(t), t); await wait(ms); return page.evaluate(() => { const a = [...document.querySelectorAll('#transcript .turn.agent .answer')].pop(); const tools = [...document.querySelectorAll('#transcript .turn.agent:last-child .tool .name')].map(n => n.textContent); return { answer: a && a.textContent.slice(0, 220), tools }; }); };
  console.log('A', JSON.stringify(await say('帶我去台北101', 5000))); await page.screenshot({ path: path.join(out, 'shot-2-101.jpg'), type: 'jpeg', quality: 84 });
  console.log('B', JSON.stringify(await say('信義區有哪些都更單元', 4500))); await page.screenshot({ path: path.join(out, 'shot-3-renewal.jpg'), type: 'jpeg', quality: 84 });
  console.log('C', JSON.stringify(await say('最近一年信義區上市公司買了什麼', 4500))); await page.screenshot({ path: path.join(out, 'shot-4-mops.jpg'), type: 'jpeg', quality: 84 });
  console.log('D', JSON.stringify(await say('2028 年南港會長出什麼', 5000))); await page.screenshot({ path: path.join(out, 'shot-5-future.jpg'), type: 'jpeg', quality: 84 });
  await page.evaluate(() => { window.PL.ui.setSensor('thermal'); }); await wait(1500); await page.screenshot({ path: path.join(out, 'shot-6-thermal.jpg'), type: 'jpeg', quality: 84 }); await page.evaluate(() => window.PL.ui.setSensor('normal'));
  console.log('E', JSON.stringify(await say('街景模式看南港軟體園區', 5000))); await page.screenshot({ path: path.join(out, 'shot-7-street.jpg'), type: 'jpeg', quality: 84 });
  // Direction C: density modes, numbered callouts, pins
  await page.evaluate(() => window.PL.ui.setDensity('immersive')); await wait(1200); await page.screenshot({ path: path.join(out, 'shot-10-immersive.jpg'), type: 'jpeg', quality: 84 });
  await page.evaluate(() => window.PL.ui.setDensity('annotated')); console.log('F', JSON.stringify(await say('最近一年信義區上市公司買了什麼', 5000))); await page.screenshot({ path: path.join(out, 'shot-11-annotated.jpg'), type: 'jpeg', quality: 84 });
  const callouts = await page.evaluate(() => ({ callouts: document.querySelectorAll('#overlay .callout-anchor').length, list: document.querySelector('#callouts') && document.querySelector('#callouts').textContent.slice(0, 80), pinsSection: !!document.querySelector('[data-pin]') })); console.log('callouts', JSON.stringify(callouts));
  await page.evaluate(() => { const b = window.PL.data.buildings.find(x => /101/.test(x.name)); window.PL.ui.select(b, 'stock'); window.PL.ui.pin(b, 'stock'); window.PL.ui.setDensity('balanced'); window.PL.map.flyTo(b.lon, b.lat, { range: 1400, pitch: -40, duration: 0.2 }); }); await wait(2500); await page.screenshot({ path: path.join(out, 'shot-12-pin.jpg'), type: 'jpeg', quality: 84 });
  const pinState = await page.evaluate(() => ({ pins: document.querySelectorAll('#overlay .anchor.pin').length, behind: document.querySelectorAll('#overlay .anchor.behind').length, mcp: document.querySelector('#mcpstat span').textContent })); console.log('pin', JSON.stringify(pinState));
  // themes, clusters, time-lapse motion, voices
  await page.evaluate(() => { window.PL.ui.setTheme('light'); window.PL.map.flyTo(121.548, 25.05, { range: 12000, pitch: -58, heading: 10, duration: 0.2 }); }); await wait(4500); await page.screenshot({ path: path.join(out, 'shot-13-light-clusters.jpg'), type: 'jpeg', quality: 84 });
  const clusters = await page.evaluate(() => { const ds = window.PL.layers.ds.markers; return { markers: ds.entities.values.length, clustering: ds.clustering.enabled, theme: window.PL.ui.theme, osmPalette: window.PL.osm && window.PL.osm.palette }; }); console.log('clusters', JSON.stringify(clusters));
  await page.evaluate(() => { window.PL.ui.setDensity('balanced'); window.PL.map.flyTo(121.5655, 25.0375, { range: 2600, pitch: -42, heading: 25, duration: 0.2 }); }); await wait(3000); await page.screenshot({ path: path.join(out, 'shot-14-light-xinyi.jpg'), type: 'jpeg', quality: 84 });
  await page.evaluate(() => { window.PL.map.setYear(2012); window.PL.ui.userMode('timelapse'); }); await wait(3600); await page.screenshot({ path: path.join(out, 'shot-15-timelapse.jpg'), type: 'jpeg', quality: 84 });
  const lapse = await page.evaluate(() => ({ year: window.PL.map.year, hud: document.querySelector('#yearhud') && document.querySelector('#yearhud').textContent.slice(0, 60), fx: window.PL.layers.ds.fx.entities.values.length })); console.log('lapse', JSON.stringify(lapse)); await page.evaluate(() => window.PL.ui.userMode('city')); await wait(3500); // let the city flight settle before testing the rig
  await page.evaluate(() => window.PL.map.rig.rotateBy(60)); await wait(1500); const hp = await page.evaluate(() => [Math.round(window.PL.map.heading), Math.round(window.PL.map.pitch)]); console.log('after rotateBy(60): heading/pitch', hp);
  console.log('voices', JSON.stringify(await page.evaluate(() => window.PL.ui.speech.voices().map(v => `${v.id}:${v.available ? 'ok' : 'n/a'}${v.prerendered ? ':pre' : ''}`))));
  // renewal simulator
  await page.evaluate(() => window.PL.ui.setDensity('balanced')); console.log('G', JSON.stringify(await say('模擬兒福B1-2及B3-2都更', 6000))); await page.screenshot({ path: path.join(out, 'shot-16-renewal-sim.jpg'), type: 'jpeg', quality: 84 });
  const simState = await page.evaluate(() => ({ card: !!document.querySelector('#simcard:not(.hidden)'), kpis: [...document.querySelectorAll('#simcard .kpi .v')].map(v => v.textContent).slice(0, 4), envelopeH: Math.round(window.PL.map.envelope.h), parcels: window.PL.layers.ds.parcels.entities.values.length })); console.log('sim', JSON.stringify(simState));
  await page.evaluate(() => { const sl = document.querySelector('#sim-bonus'); if (sl) { sl.value = 50; sl.dispatchEvent(new Event('input')); } }); await wait(1500); console.log('sim@50%', JSON.stringify(await page.evaluate(() => ({ envelopeH: Math.round(window.PL.map.envelope.h), floors: document.querySelectorAll('#simcard .kpi .v')[1].textContent }))));
  // sun & shadows (golden hour), hover mini-card, share deep link
  await page.evaluate(() => { window.PL.ui.clearSim(); window.PL.ui.setSun(17); window.PL.map.flyTo(121.5655, 25.0375, { range: 1900, pitch: -36, heading: 300, duration: 0.2 }); }); await wait(5000); await page.screenshot({ path: path.join(out, 'shot-17-golden-shadows.jpg'), type: 'jpeg', quality: 84 });
  console.log('sun', JSON.stringify(await page.evaluate(() => ({ shadows: window.PL.viewer.shadows, hour: window.PL.ui.sunHour, alt: window.PL.lighting.sunAltitude(), casters: window.PL.osm.primitives.filter(p => p.shadows === 1).length, pill: ((document.querySelector('#look') || document.querySelector('#sun') || {}).textContent || '').trim(), lighting: window.PL.viewer.scene.globe.enableLighting }))));
  await page.evaluate(() => { const b = window.PL.data.buildings.find(x => /101/.test(x.name)); window.PL.map.flyTo(b.lon, b.lat, { range: 700, pitch: -35, heading: 20, duration: 0.2 }); }); await wait(2500);
  let hov = null; for (const [dx, dy] of [[0, 0], [0, -60], [0, -140], [30, -100], [-30, -100], [0, 40]]) { await page.mouse.move(720 + dx, 450 + dy); await wait(350); hov = await page.evaluate(() => { const c = document.querySelector('#hovercard'); return { visible: !c.classList.contains('hidden'), text: c.textContent.slice(0, 90) }; }); if (hov.visible) break; }
  console.log('hover', JSON.stringify(hov)); await page.screenshot({ path: path.join(out, 'shot-18-hover.jpg'), type: 'jpeg', quality: 84 });
  const shareUrl = await page.evaluate(() => window.PL.ui.shareView()); console.log('share', shareUrl.slice(shareUrl.indexOf('#'), shareUrl.indexOf('#') + 120));
  // Phase 9D: landmark building:part geometry + DEMO_LIVE fixtures (server started with PEAKLENS_DEMO_LIVE=1 by this script)
  console.log('parts', JSON.stringify(await page.evaluate(() => ({ buildings: window.PL.osm.count, parts: window.PL.osm.partCount, prims: window.PL.osm.primitives.length }))));
  await page.evaluate(() => { const C = window.PL.Cesium; window.PL.rig.stopOrbit && window.PL.rig.stopOrbit(); window.PL.viewer.camera.setView({ destination: C.Cartesian3.fromDegrees(121.5619, 25.0318, 520), orientation: { heading: C.Math.toRadians(35), pitch: C.Math.toRadians(-22), roll: 0 } }); window.PL.compose && window.PL.compose.apply(true); }); await wait(2500); await page.screenshot({ path: path.join(out, 'shot-31-101-parts.jpg'), type: 'jpeg', quality: 84 });
  { const badge = await page.evaluate(() => { const b = document.querySelector('#envbadge, .envbadge, [data-envbadge]') || [...document.querySelectorAll('#topbar .status *')].find(x => /AQI/.test(x.textContent || '')); if (!b) return { found: false }; const r = b.getBoundingClientRect(); return { found: true, text: b.textContent.trim().slice(0, 60), right: Math.round(r.right), innerWidth, onCanvas: r.right <= innerWidth && r.width > 0, demo: /DEMO/.test(b.textContent) }; }); console.log('envbadge', JSON.stringify(badge)); }
  // live data + walkshed fallback (no keys in the sandbox: badge hidden, /api/env nulls, walkshed → estimate rings)
  console.log('live', JSON.stringify(await page.evaluate(async () => { const env = await fetch('/api/env').then(r => r.json()).catch(e => ({ err: e.message })); const ws = await fetch('/api/walkshed?lon=121.56&lat=25.03').then(r => ({ status: r.status })).catch(e => ({ err: e.message })); const badge = document.querySelector('#envbadge'); return { env: { weather: env.weather, aqi: env.aqi, available: env.available }, walkshedStatus: ws.status, badgeHidden: !badge || badge.hidden || getComputedStyle(badge).display === 'none', youbikeBtn: !!document.querySelector('[data-live="youbike"]') }; })));
  await page.evaluate(() => window.PL.ui.setYouBike(true)); await wait(1500); console.log('youbike', JSON.stringify(await page.evaluate(() => ({ on: window.PL.map.youbikeOn, count: window.PL.youbike ? window.PL.youbike.count : null })))); await page.evaluate(() => window.PL.ui.setYouBike(false));
  console.log('J', JSON.stringify(await say('這裡走路15分鐘能到哪', 6000))); await page.screenshot({ path: path.join(out, 'shot-26-walkshed.jpg'), type: 'jpeg', quality: 84 });
  console.log('walkshed', JSON.stringify(await page.evaluate(() => ({ active: window.PL.map.walkshedActive, n: window.PL.walkshed ? window.PL.walkshed.ds.entities.values.length : null })))); await page.evaluate(() => window.PL.map.clearWalkshed());
  // MRT isochrone (network computed in-app) + presenter mode
  console.log('I', JSON.stringify(await say('從南港軟體園區搭捷運20分鐘能到哪', 5000))); await page.screenshot({ path: path.join(out, 'shot-24-isochrone.jpg'), type: 'jpeg', quality: 84 });
  console.log('iso', JSON.stringify(await page.evaluate(() => ({ active: window.PL.map.isochroneActive, n: window.PL.isochrone ? window.PL.isochrone.ds.entities.values.length : null }))));
  await page.evaluate(() => { window.PL.map.clearIsochrone(); window.PL.ui.presenter.enter(); }); await wait(1500); await page.screenshot({ path: path.join(out, 'shot-25-presenter.jpg'), type: 'jpeg', quality: 84 });
  console.log('presenter', JSON.stringify(await page.evaluate(() => ({ active: window.PL.presenter.active, body: document.body.className, progress: (document.querySelector('#presenter-progress') || {}).textContent || null })))); await page.keyboard.press('Escape'); await wait(800); console.log('presenter after Esc', JSON.stringify(await page.evaluate(() => ({ active: window.PL.presenter.active, density: window.PL.ui.density }))));
  // focus / x-ray + company-move trips
  await page.evaluate(() => { const b = window.PL.data.buildings.find(x => /101/.test(x.name)); window.PL.ui.select(b, 'stock'); window.PL.ui.focus(b, 'stock', true); window.PL.map.flyTo(b.lon, b.lat, { range: 700, pitch: -40, heading: 300, duration: 0.2 }); }); await wait(5000); await page.screenshot({ path: path.join(out, 'shot-22-focus.jpg'), type: 'jpeg', quality: 84 });
  console.log('focus', JSON.stringify(await page.evaluate(() => ({ active: !!window.PL.focus.active, osm: !!window.PL.osm.focused, body: document.body.className.includes('focusing') }))));
  await page.evaluate(() => window.PL.ui.focus(null, null, false)); await wait(1500);
  // Phase 9: composer (scale budget + Look presets) and explain mode
  const jump = (lon, lat, h, heading, pitch) => page.evaluate(([lon, lat, h, heading, pitch]) => { const C = window.PL.Cesium; window.PL.rig.stopOrbit && window.PL.rig.stopOrbit(); window.PL.viewer.camera.setView({ destination: C.Cartesian3.fromDegrees(lon, lat, h), orientation: { heading: C.Math.toRadians(heading), pitch: C.Math.toRadians(pitch), roll: 0 } }); window.PL.compose.apply(true); return window.PL.compose.scale; }, [lon, lat, h, heading, pitch]);
  { console.log('jump S1 ->', await jump(121.548, 25.047, 11500, 10, -62)); await wait(800);
    const looks = {}; for (const l of ['white', 'sun', 'golden', 'night']) { const r = await page.evaluate(async (l) => { const r = await window.PL.compose.setLook(l, { quiet: true }); window.PL.compose.apply(true); const q = window.PL.viewerApi.quality; return { ok: r.ok, scale: window.PL.compose.scale, bloom: q.bloom, hdr: q.hdr, ao: q.ao, theme: window.PL.ui.theme, basemap: window.PL.viewerApi.basemapKey }; }, l); looks[l] = r; if (l === 'night') { await wait(1500); await page.screenshot({ path: path.join(out, 'shot-27-night-S1.jpg'), type: 'jpeg', quality: 84 }); } }
    console.log('looks@S1', JSON.stringify(looks));
    const labelsAt = () => page.evaluate(() => { const t = window.PL.viewer.clock.currentTime; let shown = 0, total = 0; for (const ds of Object.values(window.PL.layers.ds)) for (const e of ds.entities.values) { if (!e.label) continue; total++; const v = e.label.show && e.label.show.getValue ? e.label.show.getValue(t) : e.label.show; if (v !== false && ds.show) shown++; } return { scale: window.PL.compose.scale, shown, total }; });
    console.log('labels@S1', JSON.stringify(await labelsAt()));
    await page.evaluate(() => window.PL.compose.setLook('golden', { quiet: true })); console.log('jump S4 ->', await jump(121.5665, 25.0305, 380, 20, -35)); await wait(800); await page.evaluate(() => window.PL.compose.apply(true));
    console.log('golden@S4', JSON.stringify(await page.evaluate(() => ({ scale: window.PL.compose.scale, q: window.PL.viewerApi.quality, look: window.PL.compose.look })))); await page.screenshot({ path: path.join(out, 'shot-28-golden-S4.jpg'), type: 'jpeg', quality: 84 });
    await page.evaluate(() => window.PL.compose.setLook('white', { quiet: true })); console.log('jump S3 ->', await jump(121.5665, 25.031, 1300, 25, -42)); await wait(800); await page.evaluate(() => window.PL.compose.apply(true));
    console.log('labels@S3', JSON.stringify(await labelsAt())); await page.screenshot({ path: path.join(out, 'shot-29-white-S3.jpg'), type: 'jpeg', quality: 84 });
    const ex = await page.evaluate(async () => { if (!window.PL.explain) return { missing: true }; const keys = window.PL.data.buildings.filter(b => /信義/.test(b.district || '')).slice(0, 3).map(b => 'stock:' + b.id); const u = (window.PL.data.urban_renewal || []).find(x => x.rings); if (u) keys.push('renewal:' + u.id); const ok = window.PL.explain.enter(keys, { text: '信義區最近 12 個月：3 筆上市櫃不動產交易公告，總額約 4.9 億元。' }); return { ok, keys: keys.length }; });
    await wait(3500); const exState = await page.evaluate(() => ({ active: !!(window.PL.explain && window.PL.explain.active), callouts: document.querySelectorAll('#explain-callouts .callout, .explain-callout, .callout').length, card: !!document.querySelector('#explain-card:not(.hidden)'), vignette: !!document.querySelector('#explain-vignette') }));
    await page.screenshot({ path: path.join(out, 'shot-30-explain.jpg'), type: 'jpeg', quality: 84 }); console.log('explain', JSON.stringify({ ...ex, ...exState }));
    await page.mouse.move(720, 500); await page.mouse.down(); await page.mouse.up(); await wait(600); console.log('explain after pointerdown', JSON.stringify(await page.evaluate(() => ({ active: !!(window.PL.explain && window.PL.explain.active) })))); }
  // Phase 9F: value time machine (district choropleth from timeseries.json)
  { const tm = await page.evaluate(() => { const t = window.PL.timemachine; if (!t) return { missing: true }; const c16 = t.cityStats(2016), c26 = t.cityStats(2026); return { source: t.source, metric: t.metric, c16: { salesAll: c16.salesAll, licenses: c16.licenses, yoy: c16.yoyPct == null ? null : +c16.yoyPct.toFixed(3) }, c26: { salesAll: c26.salesAll, ytd: c26.ytd }, insufficient2015: t.isInsufficient('sales_office', 2015) }; }); console.log('timemachine', JSON.stringify(tm));
    console.log('jump S1 ->', await jump(121.548, 25.047, 11500, 10, -62)); await page.evaluate(() => { window.PL.ui.setLayer && window.PL.ui.setLayer('tm', true); window.PL.map.setYear(2013); }); await wait(1500);
    const tmA = await page.evaluate(() => ({ year: window.PL.map.year, show: window.PL.layers.ds.tm && window.PL.layers.ds.tm.show, mask: window.PL.layers.mask && window.PL.layers.mask.tm, n: window.PL.layers.ds.tm ? window.PL.layers.ds.tm.entities.values.length : 0, hud: (document.querySelector('#yearhud') || {}).textContent }));
    await page.screenshot({ path: path.join(out, 'shot-32-timemachine-2013.jpg'), type: 'jpeg', quality: 84 });
    await page.evaluate(() => window.PL.map.setYear(2021)); await wait(1500); const tmB = await page.evaluate(() => ({ year: window.PL.map.year, hud: (document.querySelector('#yearhud') || {}).textContent }));
    await page.screenshot({ path: path.join(out, 'shot-33-timemachine-2021.jpg'), type: 'jpeg', quality: 84 }); console.log('tm@S1', JSON.stringify({ a: tmA, b: tmB }));
    console.log('jump S3 ->', await jump(121.5665, 25.031, 1300, 25, -42)); await wait(800); console.log('tm@S3', JSON.stringify(await page.evaluate(() => ({ show: window.PL.layers.ds.tm && window.PL.layers.ds.tm.show, mask: window.PL.layers.mask && window.PL.layers.mask.tm }))));
    await page.evaluate(() => { window.PL.map.setYear(2026); window.PL.compose.setLook('white', { quiet: true }); }); }
  // Phase 10: photoreal availability/fallback, frames, voice bar, stage, insights
  { const p10 = await page.evaluate(() => ({ photoreal: window.PL.photoreal ? { available: window.PL.photoreal.available, status: window.PL.photoreal.status, active: window.PL.photoreal.active } : null, look: window.PL.compose.look, frames: window.PL.frames ? { count: window.PL.frames.count, future: window.PL.frames.futureCount } : null, voicebar: !!document.querySelector('#voicebar'), cinebar: !!document.querySelector('#cinebar'), caption: !!document.querySelector('#caption'), stage: !!window.PL.stage, insights: !!window.PL.insights, aiMode: window.PL.ui.claudeMode }));
    console.log('p10', JSON.stringify(p10));
    console.log('jump S3 ->', await jump(121.5665, 25.031, 900, 25, -42)); await page.evaluate(() => window.PL.ui.setDensity('annotated')); await wait(2500);
    const ins = await page.evaluate(() => ({ chips: window.PL.insights ? window.PL.insights.chips.length : null, visible: !!document.querySelector('#insights:not(.hidden)'), text: (document.querySelector('#insights') || {}).textContent ? document.querySelector('#insights').textContent.replace(/\s+/g, ' ').trim().slice(0, 140) : null })); console.log('insights', JSON.stringify(ins));
    await page.screenshot({ path: path.join(out, 'shot-34-annotated-insights.jpg'), type: 'jpeg', quality: 84 });
    await page.evaluate(() => window.PL.ui.setDensity('immersive')); await wait(1200); await page.screenshot({ path: path.join(out, 'shot-35-immersive.jpg'), type: 'jpeg', quality: 84 }); await page.evaluate(() => window.PL.ui.setDensity('balanced'));
    // scene with stage takeover + voice bar (speech is silent/instant here): sample state during the first seconds
    await page.evaluate(() => { window.PL.director.play('investor'); }); await wait(4000); // block body: do not await the whole scene
    const sc = await page.evaluate(() => ({ playing: window.PL.director.playing, paused: !!window.PL.director.paused, voicebarText: (document.querySelector('#voicebar') || {}).textContent ? document.querySelector('#voicebar').textContent.trim().slice(0, 80) : null, presenting: document.body.classList.contains('presenting'), look: window.PL.compose.look, density: window.PL.ui.density }));
    await page.screenshot({ path: path.join(out, 'shot-36-scene-stage.jpg'), type: 'jpeg', quality: 84 }); console.log('scene', JSON.stringify(sc));
    await page.evaluate(() => window.PL.director.pause && window.PL.director.pause()); await wait(300); console.log('scene paused', JSON.stringify(await page.evaluate(() => ({ paused: !!window.PL.director.paused }))));
    await page.evaluate(() => window.PL.director.stop()); await wait(800); console.log('scene stopped', JSON.stringify(await page.evaluate(() => ({ playing: window.PL.director.playing, look: window.PL.compose.look, density: window.PL.ui.density })))); }
  console.log('H', JSON.stringify(await say('播放企業遷徙動線', 1500))); await page.evaluate(() => { window.PL.trips.clear(); window.PL.trips.play({ year: 2026, max: 6, durationMs: 9000, staggerMs: 300 }); }); await wait(2500); await page.screenshot({ path: path.join(out, 'shot-23-trips.jpg'), type: 'jpeg', quality: 84 });
  console.log('trips', JSON.stringify(await page.evaluate(() => ({ playing: window.PL.trips && window.PL.trips.playing, entities: window.PL.viewer.dataSources.getByName('trips').length ? window.PL.viewer.dataSources.getByName('trips')[0].entities.values.length : null }))));
  await page.evaluate(() => window.PL.trips.clear()); await wait(800);
  await page.mouse.move(5, 5); await page.evaluate(() => { window.PL.ui.setSun(null); window.PL.ui.setOverlay('landsect', true); window.PL.ui.setOverlay('publicland', true); }); await wait(2500); await page.screenshot({ path: path.join(out, 'shot-20-overlays.jpg'), type: 'jpeg', quality: 84 });
  console.log('overlays', JSON.stringify(await page.evaluate(() => ({ on: window.PL.ui.overlays(), imagery: window.PL.viewer.imageryLayers.length, credits: document.querySelector('#credits').textContent.slice(0, 120), ground: window.PL.ground && window.PL.ground.counts, rivers: !!(window.PL.ground && window.PL.ground.rivers), quality: window.PL.viewerApi.quality }))));
  await page.evaluate(() => { window.PL.ui.setOverlay('landsect', false); window.PL.ui.setOverlay('publicland', false); window.PL.ui.setTheme('dark'); window.PL.map.flyTo(121.51, 25.07, { range: 5200, pitch: -48, heading: 135, duration: 0.2 }); }); await wait(4000); await page.screenshot({ path: path.join(out, 'shot-21-night-rivers.jpg'), type: 'jpeg', quality: 84 });
  console.log('night', JSON.stringify(await page.evaluate(() => ({ quality: window.PL.viewerApi.quality, bloom: window.PL.viewer.scene.postProcessStages.bloom.enabled, roadsShown: window.PL.ground ? window.PL.ground.roads.filter(p => p.show).length : 0, basemapYear: window.PL.viewerApi.basemapYear }))));
  await page.evaluate(() => { window.PL.map.setYear(2016); }); await wait(600); console.log('vintage', JSON.stringify(await page.evaluate(() => ({ year: window.PL.map.year, basemapYear: window.PL.viewerApi.basemapYear })))); await page.evaluate(() => window.PL.map.setYear(2026));
  await page.evaluate(() => window.PL.director.play('investor')); await wait(9000); await page.screenshot({ path: path.join(out, 'shot-8-scene.jpg'), type: 'jpeg', quality: 84 });
  const cine = await page.evaluate(() => document.querySelector('#cine-text').textContent); console.log('scene text:', cine);
  await page.evaluate(() => window.PL.director.stop());
  await page.evaluate(() => window.PL.map.globe()); await wait(4000); await page.screenshot({ path: path.join(out, 'shot-9-globe.jpg'), type: 'jpeg', quality: 84 });
  const health = await page.evaluate(() => fetch('/api/health').then(r => r.json())); console.log('health', JSON.stringify(health));
  page.on('console', m => { if (m.type() === 'error' && !/net::|ERR_|404/.test(m.text())) console.log('[reload console]', m.text().slice(0, 400)); }); page.on('pageerror', e => console.log('[reload pageerror]', e.message.slice(0, 400)));
  { const t2 = Date.now(); await page.goto('about:blank'); await page.goto(shareUrl, { waitUntil: 'domcontentloaded', timeout: 120000 }); /* via about:blank: a hash-only change would not reload */ await page.waitForSelector('#loading.done', { timeout: 240000 }); for (let i = 0; i < 40 && !(await page.evaluate(() => !!window.PL)); i++) await wait(1500); await wait(2000);
    console.log('deeplink', JSON.stringify(await page.evaluate(() => window.PL ? ({ theme: window.PL.ui.theme, density: window.PL.ui.density, sun: window.PL.ui.sunHour, lens: window.PL.agent.lens, year: window.PL.map.year, heading: Math.round(window.PL.map.heading), pitch: Math.round(window.PL.map.pitch), h: Math.round(window.PL.rig.lonlat[2]), hash: location.hash.slice(0, 40) }) : ({ FAILED: 'no window.PL after reload', loadmsg: (document.querySelector('#loadmsg') || {}).textContent, loading: (document.querySelector('#loading') || {}).className, hash: location.hash.slice(0, 80), stored: { theme: localStorage.getItem('pl.theme'), density: localStorage.getItem('pl.density') } }))), 'in', Date.now() - t2, 'ms'); if (!(await page.evaluate(() => !!window.PL))) errors.push('deeplink: app object missing after reload'); await page.screenshot({ path: path.join(out, 'shot-19-deeplink.jpg'), type: 'jpeg', quality: 80 }); }
} catch (e) { console.error('SMOKE FAILED', e); errors.push('fatal: ' + e.message); await page.screenshot({ path: path.join(out, 'shot-fail.jpg'), type: 'jpeg', quality: 84 }).catch(() => {}); }
console.log('errors:', errors.length); for (const e of [...new Set(errors)].slice(0, 25)) console.log('  -', e); console.log('expected keyless fallbacks:', expected.length, [...new Set(expected)].slice(0, 6).join(' | '));
await browser.close(); server.kill();
process.exit(errors.some(e => e.startsWith('pageerror') || e.startsWith('fatal')) ? 1 : 0);
